# ACTIVIDAD 3 FACTORES CUALITATIVOS

Claudio Alejo Encarnación Martínez (750597)

## Codificación de variables categóricas

### Con librerías básicas

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('/Users/claudioalejoencarnacionmartinez/Documents/SEMESTRE OTOÑO 2026/LAB APRENDIZAJE ESTADÍSTICO/LABORATORIO-DE-APRENDIZAJE-ESTAD-STICO/FEO.csv')
df.head()

  SABOR TAMANO HIELO  CALIFICACION
0     N     CH    SI           8.5
1     N     CH    NO           7.0
2     N      G    SI           9.0
3     N      G    NO           7.5
4     C     CH    SI           7.5

In [10]:
df.describe()

       CALIFICACION
count     20.000000
mean       7.600000
std        1.262829
min        5.000000
25%        7.000000
50%        7.500000
75%        8.500000
max       10.000000

df['SABOR'].unique() me da cuantos datos diferentes hay en la columna

In [11]:
print(df['SABOR'].unique())
print(df['TAMANO'].unique())
print(df['HIELO'].unique())
print(df['CALIFICACION'].unique())

<StringArray>
['N', 'C', 'K', 'FP', 'S']
Length: 5, dtype: str
<StringArray>
['CH', 'G']
Length: 2, dtype: str
<StringArray>
['SI', 'NO']
Length: 2, dtype: str
[ 8.5  7.   9.   7.5  6.   8.  10.   5. ]

Cambiar variables de tamaño y hielo a valores 0 y 1

In [12]:
#Codificar la columna TAMANO, para que CH sea 0 y G sea 1
df['TAMANO'] = df['TAMANO'].map({'CH': 0, 'G': 1})
df['TAMANO'].unique()

array([0, 1])

In [13]:
#Codificar la columna HIELO, para que SI sea 1 y NO sea 0
df['HIELO'] = df['HIELO'].map({'SI': 1, 'NO': 0})
df['HIELO'].unique()

array([1, 0])

In [14]:
df.head()

  SABOR  TAMANO  HIELO  CALIFICACION
0     N       0      1           8.5
1     N       0      0           7.0
2     N       1      1           9.0
3     N       1      0           7.5
4     C       0      1           7.5

In [30]:
#Separar la columna SABOR en 5 columnas, una para cada sabor, empezar con columna NARANJA, tomando si el dato contiene "N" o no
df['NARANJA'] = df['SABOR'].str.contains('N')
df['COCO'] = df['SABOR'].str.contains('C')
df['FRESAPINA'] = df['SABOR'].str.contains('FP')
df['KAHLUA'] = df['SABOR'].str.contains('K')
df['SANDIA'] = df['SABOR'].str.contains('S')
df.head()

,SABOR,TAMANO,HIELO,CALIFICACION,NARANJA,COCO,FRESAPINA,KAHLUA,SANDIA
0,N,0,1,8.5,True,False,False,False,False
1,N,0,0,7.0,True,False,False,False,False
2,N,1,1,9.0,True,False,False,False,False
3,N,1,0,7.5,True,False,False,False,False
4,C,0,1,7.5,False,True,False,False,False

In [31]:
#Eliminar columna SABOR
df = df.drop(columns=['SABOR'])
df.head()

   TAMANO  HIELO  CALIFICACION  NARANJA   COCO  FRESAPINA  KAHLUA  SANDIA
0       0      1           8.5     True  False      False   False   False
1       0      0           7.0     True  False      False   False   False
2       1      1           9.0     True  False      False   False   False
3       1      0           7.5     True  False      False   False   False
4       0      1           7.5    False   True      False   False   False

In [33]:
#Reordenar columnas al principio, primero las columnas de sabor, luego TAMANO, HIELO y CALIFICACION
df = df[['NARANJA', 'COCO', 'KAHLUA', 'FRESAPINA', 'SANDIA', 'TAMANO', 'HIELO', 'CALIFICACION']]
df.head()

   NARANJA   COCO  KAHLUA  FRESAPINA  SANDIA  TAMANO  HIELO  CALIFICACION
0     True  False   False      False   False       0      1           8.5
1     True  False   False      False   False       0      0           7.0
2     True  False   False      False   False       1      1           9.0
3     True  False   False      False   False       1      0           7.5
4    False   True   False      False   False       0      1           7.5

## Realizar la regresión con la librería con OLS

In [35]:
import statsmodels.api as sm

In [39]:
#Regresión lineal con OLS, usando todas las columnas como variables independientes y CALIFICACION como variable dependiente
X = df[['NARANJA', 'COCO', 'KAHLUA', 'FRESAPINA', 'SANDIA', 'TAMANO', 'HIELO']]
X = sm.add_constant(X)
y = df['CALIFICACION']
model = sm.OLS(y, X).fit()
model.summary()

/var/folders/yw/qyjd88g55q12jrgy7__880_w0000gn/T/ipykernel_10131/3970076138.py:5: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  model = sm.OLS(y, X).fit()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           CALIFICACION   R-squared:                       0.927
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     27.67
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           1.11e-06
Time:                        17:15:01   Log-Likelihood:                -6.3060
No. Observations:                  20   AIC:                             26.61
Df Residuals:                      13   BIC:                             33.58
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.4583      0.133     41.111      0.000       5.171       5.745
NARANJA        1.4917      0.186      8.025      0.000       1.090       1.893
COCO           0.6167      0.186      3.318      0.006       0.215       1.018
KAHLUA         2.3667      0.186     12.732      0.000       1.965       2.768
FRESAPINA      1.1167      0.186      6.007      0.000       0.715       1.518
SANDIA        -0.1333      0.186     -0.717      0.486      -0.535       0.268
TAMANO         0.5000      0.184      2.718      0.018       0.103       0.897
HIELO          1.6000      0.184      8.697      0.000       1.203       1.997
==============================================================================
Omnibus:                       15.683   Durbin-Watson:                   2.372
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               15.836
Skew:                          -1.542   Prob(JB):                     0.000364
Kurtosis:                       6.081   Cond. No.                     1.43e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.75e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

## Realizar la codificación con sklearn

In [40]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [52]:
df_sk = pd.read_csv('/Users/claudioalejoencarnacionmartinez/Documents/SEMESTRE OTOÑO 2026/LAB APRENDIZAJE ESTADÍSTICO/LABORATORIO-DE-APRENDIZAJE-ESTAD-STICO/FEO.csv')
df_sk.head()

  SABOR TAMANO HIELO  CALIFICACION
0     N     CH    SI           8.5
1     N     CH    NO           7.0
2     N      G    SI           9.0
3     N      G    NO           7.5
4     C     CH    SI           7.5

In [53]:
#Codificar la columna TAMANO, para que CH sea 0 y G sea 1 con OrdinalEncoder
ordinal_encoder = OrdinalEncoder(categories=[['CH', 'G']])
df_sk['TAMANO'] = ordinal_encoder.fit_transform(df_sk[['TAMANO']])
df_sk['TAMANO'].unique()

array([0., 1.])

In [54]:
#Codificar la columna HIELO, para que SI sea 1 y NO sea 0 con OrdinalEncoder
ordinal_encoderHIELO = OrdinalEncoder(categories=[['NO', 'SI']])
df_sk['HIELO'] = ordinal_encoderHIELO.fit_transform(df_sk[['HIELO']])
df_sk['HIELO'].unique()

array([1., 0.])

In [55]:
df_sk.head(10)

  SABOR  TAMANO  HIELO  CALIFICACION
0     N     0.0    1.0           8.5
1     N     0.0    0.0           7.0
2     N     1.0    1.0           9.0
3     N     1.0    0.0           7.5
4     C     0.0    1.0           7.5
5     C     0.0    0.0           6.0
6     C     1.0    1.0           8.0
7     C     1.0    0.0           7.0
8     K     0.0    1.0           9.0
9     K     0.0    0.0           8.0

In [56]:
#Codificar la columna SABOR con OneHotEncoder con 5 columnas, una para cada sabor, empezando con NARANJA, COCO, KAHLUA, FRESAPINA y SANDIA
onehot_encoder = OneHotEncoder(categories=[['N', 'C', 'K', 'FP', 'S']])
df_sk[['NARANJA', 'COCO', 'KAHLUA', 'FRESAPINA', 'SANDIA']] = onehot_encoder.fit_transform(df_sk[['SABOR']]).toarray()
df_sk.head(10)

  SABOR  TAMANO  HIELO  CALIFICACION  NARANJA  COCO  KAHLUA  FRESAPINA  SANDIA
0     N     0.0    1.0           8.5      1.0   0.0     0.0        0.0     0.0
1     N     0.0    0.0           7.0      1.0   0.0     0.0        0.0     0.0
2     N     1.0    1.0           9.0      1.0   0.0     0.0        0.0     0.0
3     N     1.0    0.0           7.5      1.0   0.0     0.0        0.0     0.0
4     C     0.0    1.0           7.5      0.0   1.0     0.0        0.0     0.0
5     C     0.0    0.0           6.0      0.0   1.0     0.0        0.0     0.0
6     C     1.0    1.0           8.0      0.0   1.0     0.0        0.0     0.0
7     C     1.0    0.0           7.0      0.0   1.0     0.0        0.0     0.0
8     K     0.0    1.0           9.0      0.0   0.0     1.0        0.0     0.0
9     K     0.0    0.0           8.0      0.0   0.0     1.0        0.0     0.0

In [ ]:
#Borrar columna de SABOR
df_sk = df_sk.drop(columns=['SABOR'])
df_sk.head(10)

   TAMANO  HIELO  CALIFICACION  NARANJA  COCO  KAHLUA  FRESAPINA  SANDIA
0     0.0    1.0           8.5      1.0   0.0     0.0        0.0     0.0
1     0.0    0.0           7.0      1.0   0.0     0.0        0.0     0.0
2     1.0    1.0           9.0      1.0   0.0     0.0        0.0     0.0
3     1.0    0.0           7.5      1.0   0.0     0.0        0.0     0.0
4     0.0    1.0           7.5      0.0   1.0     0.0        0.0     0.0
5     0.0    0.0           6.0      0.0   1.0     0.0        0.0     0.0
6     1.0    1.0           8.0      0.0   1.0     0.0        0.0     0.0
7     1.0    0.0           7.0      0.0   1.0     0.0        0.0     0.0
8     0.0    1.0           9.0      0.0   0.0     1.0        0.0     0.0
9     0.0    0.0           8.0      0.0   0.0     1.0        0.0     0.0

In [58]:
#Reordenar columnas al principio, primero las columnas de sabor, luego TAMANO, HIELO y CALIFICACION
df_sk = df_sk[['NARANJA', 'COCO', 'KAHLUA', 'FRESAPINA', 'SANDIA', 'TAMANO', 'HIELO', 'CALIFICACION']]
df_sk.head(5)

   NARANJA  COCO  KAHLUA  FRESAPINA  SANDIA  TAMANO  HIELO  CALIFICACION
0      1.0   0.0     0.0        0.0     0.0     0.0    1.0           8.5
1      1.0   0.0     0.0        0.0     0.0     0.0    0.0           7.0
2      1.0   0.0     0.0        0.0     0.0     1.0    1.0           9.0
3      1.0   0.0     0.0        0.0     0.0     1.0    0.0           7.5
4      0.0   1.0     0.0        0.0     0.0     0.0    1.0           7.5

Rehaciendo la regresión

In [59]:
X_sk = df_sk[['NARANJA', 'COCO', 'KAHLUA', 'FRESAPINA', 'SANDIA', 'TAMANO', 'HIELO']]
X_sk = sm.add_constant(X_sk)
y_sk = df_sk['CALIFICACION']
model_sk = sm.OLS(y_sk, X_sk).fit()
model_sk.summary()

/var/folders/yw/qyjd88g55q12jrgy7__880_w0000gn/T/ipykernel_10131/488218843.py:4: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  model_sk = sm.OLS(y_sk, X_sk).fit()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           CALIFICACION   R-squared:                       0.927
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     27.67
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           1.11e-06
Time:                        17:39:21   Log-Likelihood:                -6.3060
No. Observations:                  20   AIC:                             26.61
Df Residuals:                      13   BIC:                             33.58
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.4583      0.133     41.111      0.000       5.171       5.745
NARANJA        1.4917      0.186      8.025      0.000       1.090       1.893
COCO           0.6167      0.186      3.318      0.006       0.215       1.018
KAHLUA         2.3667      0.186     12.732      0.000       1.965       2.768
FRESAPINA      1.1167      0.186      6.007      0.000       0.715       1.518
SANDIA        -0.1333      0.186     -0.717      0.486      -0.535       0.268
TAMANO         0.5000      0.184      2.718      0.018       0.103       0.897
HIELO          1.6000      0.184      8.697      0.000       1.203       1.997
==============================================================================
Omnibus:                       15.683   Durbin-Watson:                   2.372
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               15.836
Skew:                          -1.542   Prob(JB):                     0.000364
Kurtosis:                       6.081   Cond. No.                     1.43e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.75e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""