# A06 REGRESIÓN LOGÍSTICA

|                |   |
:----------------|---|
| **Nombre**     | Claudio Alejo Encarnación Martínez |
| **Fecha**      |  1 octubre 2026 |
| **Expediente** |  750597 |

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('/Users/claudioalejoencarnacionmartinez/Documents/SEMESTRE OTOÑO 2026/LAB APRENDIZAJE ESTADÍSTICO/LABORATORIO-DE-APRENDIZAJE-ESTAD-STICO/Heart Prediction Quantum Dataset.csv')
df.head()

   Age     Gender BloodPressure  Cholesterol  HeartRate  HeartDisease
0   68  Hombre           105.00          191        107             1
1   58      Mujer         97.00          249         89             0
2   44      Mujer         93.00          190         82             1
3   72  Hombre            93.00          183        101             1
4   37      Mujer        145.00          166        103             1

### Limpieza de datos hecho en Lab 3

In [3]:
#Cambiar el punto decimal de europeo a americano en la columna de BloodPressure
df['BloodPressure'] = df['BloodPressure'].str.replace(',', '.').astype(float)
df['BloodPressure'].head()

df['Gender'] = df['Gender'].str.lower()
df['Gender'] = df['Gender'].str.rstrip("   ")
df['Gender'] = df['Gender'].str.rstrip("}",).str.rstrip("{")
df['Gender'] = df['Gender'].replace('ombre', 'hombre')
df['Gender'] = df['Gender'].map({'hombre': 1, 'mujer': 0})

df = df.drop_duplicates()
df = df.dropna()

print(df['HeartDisease'].unique(), df['Gender'].unique())

[1 0] [1 0]

In [4]:
df.head()

   Age  Gender  BloodPressure  Cholesterol  HeartRate  HeartDisease
0   68       1          105.0          191        107             1
1   58       0           97.0          249         89             0
2   44       0           93.0          190         82             1
3   72       1           93.0          183        101             1
4   37       0          145.0          166        103             1

### Crear el modelo de regresión logística

In [5]:
from sklearn.linear_model import LogisticRegression

### Modelo $$ln({P}/{1-P})=\beta_0+\beta_1(BloodPressure)$$

In [6]:
X = df['BloodPressure'].values.reshape(-1, 1)
y = df['HeartDisease']

logit = LogisticRegression()

logit.fit(X, y)

print("Beta cero:", logit.intercept_[0])
print("Beta uno:", logit.coef_[0][0])

Beta cero: 1.6217289935252623
Beta uno: -0.009110712666677337

In [7]:
LogisticRegression?

Init signature:
LogisticRegression(
    penalty='deprecated',
    *,
    C=1.0,
    l1_ratio=0.0,
    dual=False,
    tol=0.0001,
    fit_intercept=True,
    intercept_scaling=1,
    class_weight=None,
    random_state=None,
    solver='lbfgs',
    max_iter=100,
    verbose=0,
    warm_start=False,
    n_jobs=None,
)
Docstring:
Logistic Regression (aka logit, MaxEnt) classifier.

This class implements regularized logistic regression using a set of available
solvers. **Note that regularization is applied by default**. It can handle both
dense and sparse input `X`. Use C-ordered arrays or CSR matrices containing 64-bit
floats for optimal performance; any other input format will be converted (and
copied).

The solvers 'lbfgs', 'newton-cg', 'newton-cholesky' and 'sag' support only L2
regularization with primal formulation, or no regularization. The 'liblinear'
solver supports both L1 and L2 regularization (but not both, i.e. elastic-net),
with a dual formulation only for the L2 penalty. The Elastic-Net (combination of L1
and L2) regularization is only supported by the 'saga' solver.

For :term:`multiclass` problems (whenever `n_classes >= 3`), all solvers except
'liblinear' optimize the (penalized) multinomial loss. 'liblinear' only handles
binary classification but can be extended to handle multiclass by using
:class:`~sklearn.multiclass.OneVsRestClassifier`.

Read more in the :ref:`User Guide <logistic_regression>`.

Parameters
----------
penalty : {'l1', 'l2', 'elasticnet', None}, default='l2'
    Specify the norm of the penalty:

    - `None`: no penalty is added;
    - `'l2'`: add an L2 penalty term and it is the default choice;
    - `'l1'`: add an L1 penalty term;
    - `'elasticnet'`: both L1 and L2 penalty terms are added.

    .. warning::
       Some penalties may not work with some solvers. See the parameter
       `solver` below, to know the compatibility between the penalty and
       solver.

    .. versionadded:: 0.19
       l1 penalty with SAGA solver (allowing 'multinomial' + L1)

    .. deprecated:: 1.8
       `penalty` was deprecated in version 1.8 and will be removed in 1.10.
       Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`,
       `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1
       for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.

C : float, default=1.0
    Inverse of regularization strength; must be a positive float.
    Like in support vector machines, smaller values specify stronger
    regularization. `C=np.inf` results in unpenalized logistic regression.
    For a visual example on the effect of tuning the `C` parameter
    with an L1 penalty, see:
    :ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.

l1_ratio : float, default=0.0
    The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting
    `l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.
    Any value between 0 and 1 gives an Elastic-Net penalty of the form
    `l1_ratio * L1 + (1 - l1_ratio) * L2`.

    .. warning::
       Certain values of `l1_ratio`, i.e. some penalties, may not work with some
       solvers. See the parameter `solver` below, to know the compatibility between
       the penalty and solver.

    .. versionchanged:: 1.8
        Default value changed from None to 0.0.

    .. deprecated:: 1.8
        `None` is deprecated and will be removed in version 1.10. Always use
        `l1_ratio` to specify the penalty type.

dual : bool, default=False
    Dual (constrained) or primal (regularized, see also
    :ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulation
    is only implemented for l2 penalty with liblinear solver. Prefer `dual=False`
    when n_samples > n_features.

tol : float, default=1e-4
    Tolerance for stopping criteria.

fit_intercept : bool, default=True
    Specifies if a constant (a.k.a. bias or intercept) should be
    added to the decision function.

intercept_scaling : float, default=1
    Useful only when the solver `liblinear` is used
    and `self.fit_intercept` is set to `True`. In this case, `x` becomes
    `[x, self.intercept_scaling]`,
    i.e. a "synthetic" feature with constant value equal to
    `intercept_scaling` is appended to the instance vector.
    The intercept becomes
    ``intercept_scaling * synthetic_feature_weight``.

    .. note::
        The synthetic feature weight is subject to L1 or L2
        regularization as all other features.
        To lessen the effect of regularization on synthetic feature weight
        (and therefore on the intercept) `intercept_scaling` has to be increased.

class_weight : dict or 'balanced', default=None
    Weights associated with classes in the form ``{class_label: weight}``.
    If not given, all classes are supposed to have weight one.

    The "balanced" mode uses the values of y to automatically adjust
    weights inversely proportional to class frequencies in the input data
    as ``n_samples / (n_classes * np.bincount(y))``.

    Note that these weights will be multiplied with sample_weight (passed
    through the fit method) if sample_weight is specified.

    .. versionadded:: 0.17
       *class_weight='balanced'*

random_state : int, RandomState instance, default=None
    Used when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle the
    data. See :term:`Glossary <random_state>` for details.

solver : {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'},             default='lbfgs'

    Algorithm to use in the optimization problem. Default is 'lbfgs'.
    To choose a solver, you might want to consider the following aspects:

    - 'lbfgs' is a good default solver because it works reasonably well for a wide
      class of problems.
    - For :term:`multiclass` problems (`n_classes >= 3`), all solvers except
      'liblinear' minimize the full multinomial loss, 'liblinear' will raise an
      error.
    - 'newton-cholesky' is a good choice for
      `n_samples` >> `n_features * n_classes`, especially with one-hot encoded
      categorical features with rare categories. Be aware that the memory usage
      of this solver has a quadratic dependency on `n_features * n_classes`
      because it explicitly computes the full Hessian matrix.
    - For small datasets, 'liblinear' is a good choice, whereas 'sag'
      and 'saga' are faster for large ones;
    - 'liblinear' can only handle binary classification by default. To apply a
      one-versus-rest scheme for the multiclass setting one can wrap it with the
      :class:`~sklearn.multiclass.OneVsRestClassifier`.

    .. warning::
       The choice of the algorithm depends on the penalty chosen (`l1_ratio=0`
       for L2-penalty, `l1_ratio=1` for L1-penalty and `0 < l1_ratio < 1` for
       Elastic-Net) and on (multinomial) multiclass support:

       ================= ======================== ======================
       solver            l1_ratio                 multinomial multiclass
       ================= ======================== ======================
       'lbfgs'           l1_ratio=0               yes
       'liblinear'       l1_ratio=1 or l1_ratio=0 no
       'newton-cg'       l1_ratio=0               yes
       'newton-cholesky' l1_ratio=0               yes
       'sag'             l1_ratio=0               yes
       'saga'            0<=l1_ratio<=1           yes
       ================= ======================== ======================

    .. note::
       'sag' and 'saga' fast convergence is only guaranteed on features
       with approximately the same scale. You can preprocess the data with
       a scaler from :mod:`sklearn.preprocessing`.

    .. seealso::
       Refer to the :ref:`User Guide <Logistic_regression>` for more
       information regarding :class:`LogisticRegression` and more specifically the
       :ref:`Table <logistic_regression_solvers>`
       summarizing solver/penalty supports.

    .. versionadded:: 0.17
       Stochastic Average Gradient (SAG) descent solver. Multinomial support in
       version 0.18.
    .. versionadded:: 0.19
       SAGA solver.
    .. versionchanged:: 0.22
       The default solver changed from 'liblinear' to 'lbfgs' in 0.22.
    .. versionadded:: 1.2
       newton-cholesky solver. Multinomial support in version 1.6.

max_iter : int, default=100
    Maximum number of iterations taken for the solvers to converge.

verbose : int, default=0
    For the liblinear and lbfgs solvers set verbose to any positive
    number for verbosity.

warm_start : bool, default=False
    When set to True, reuse the solution of the previous call to fit as
    initialization, otherwise, just erase the previous solution.
    Useless for liblinear solver. See :term:`the Glossary <warm_start>`.

    .. versionadded:: 0.17
       *warm_start* to support *lbfgs*, *newton-cg*, *sag*, *saga* solvers.

n_jobs : int, default=None
    Does not have any effect.

    .. deprecated:: 1.8
       `n_jobs` is deprecated in version 1.8 and will be removed in 1.10.

Attributes
----------

classes_ : ndarray of shape (n_classes, )
    A list of class labels known to the classifier.

coef_ : ndarray or CSR matrix of shape (1, n_features) or (n_classes, n_features)
    Coefficients of the features in the decision function.

    `coef_` is of shape (1, n_features) when the given problem is binary.

    By default, it will be created as a dense array, but can be turned to
    sparse (CSR format) through :meth:`sparsify` (which can be beneficial
    under L1 regularization when many coefficients are zero), and back to
    dense through :meth:`densify`.

intercept_ : ndarray of shape (1,) or (n_classes,)
    Intercept (a.k.a. bias) added to the decision function.

    If `fit_intercept` is set to False, the intercept is set to zero.
    `intercept_` is of shape (1,) when the given problem is binary.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

n_iter_ : ndarray of shape (1, )
    Actual number of iterations for all classes.

    .. versionchanged:: 0.20

        In SciPy <= 1.0.0 the number of lbfgs iterations may exceed
        ``max_iter``. ``n_iter_`` will now report at most ``max_iter``.

See Also
--------
SGDClassifier : Incrementally trained logistic regression (when given
    the parameter ``loss="log_loss"``).
LogisticRegressionCV : Logistic regression with built-in cross validation.

Notes
-----
The underlying C implementation uses a random number generator to
select features when fitting the model. It is thus not uncommon,
to have slightly different results for the same input data. If
that happens, try with a smaller tol parameter.

Predict output may not match that of standalone liblinear in certain
cases. See :ref:`differences from liblinear <liblinear_differences>`
in the narrative documentation.

References
----------

L-BFGS-B -- Software for Large-scale Bound-constrained Optimization
    Ciyou Zhu, Richard Byrd, Jorge Nocedal and Jose Luis Morales.
    http://users.iems.northwestern.edu/~nocedal/lbfgsb.html

LIBLINEAR -- A Library for Large Linear Classification
    https://www.csie.ntu.edu.tw/~cjlin/liblinear/

SAG -- Mark Schmidt, Nicolas Le Roux, and Francis Bach
    Minimizing Finite Sums with the Stochastic Average Gradient
    https://hal.inria.fr/hal-00860051/document

SAGA -- Defazio, A., Bach F. & Lacoste-Julien S. (2014).
        :arxiv:`"SAGA: A Fast Incremental Gradient Method With Support
        for Non-Strongly Convex Composite Objectives" <1407.0202>`

Hsiang-Fu Yu, Fang-Lan Huang, Chih-Jen Lin (2011). Dual coordinate descent
    methods for logistic regression and maximum entropy models.
    Machine Learning 85(1-2):41-75.
    https://www.csie.ntu.edu.tw/~cjlin/papers/maxent_dual.pdf

Examples
--------
>>> from sklearn.datasets import load_iris
>>> from sklearn.linear_model import LogisticRegression
>>> X, y = load_iris(return_X_y=True)
>>> clf = LogisticRegression(random_state=0).fit(X, y)
>>> clf.predict(X[:2, :])
array([0, 0])
>>> clf.predict_proba(X[:2, :])
array([[9.82e-01, 1.82e-02, 1.44e-08],
       [9.72e-01, 2.82e-02, 3.02e-08]])
>>> clf.score(X, y)
0.97

For a comparison of the LogisticRegression with other classifiers see:
:ref:`sphx_glr_auto_examples_classification_plot_classification_probability.py`.
File:           /opt/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py
Type:           type
Subclasses:     LogisticRegressionCV

- **Nota:** La función de LogisticRegression() incluye regularización, por default usa L2
- **Nota:** El parámetro C=1 es la fuerza de penalización, mientras más pequeño más penalización, y vicerversa. A continuación un ejemplo:

#### Efecto de la penalización (C=?)

In [8]:
X = df['BloodPressure'].values.reshape(-1, 1)
y = df['HeartDisease']

logit1 = LogisticRegression(C=1E-6)

logit1.fit(X, y)

print("Beta cero:", logit1.intercept_[0])
print("Beta uno:", logit1.coef_[0][0])

Beta cero: 0.49822720410035487
Beta uno: -0.0006978645382854838

In [9]:
X = df['BloodPressure'].values.reshape(-1, 1)
y = df['HeartDisease']

logit2 = LogisticRegression(C=1E6)

logit2.fit(X, y)

print("Beta cero:", logit2.intercept_[0])
print("Beta uno:", logit2.coef_[0][0])

Beta cero: 1.6217439478286584
Beta uno: -0.00911082417460399

In [10]:
logit.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
logit.predict_proba(X)

array([[0.33959397, 0.66040603],
       [0.32344386, 0.67655614],
       [0.315521  , 0.684479  ],
       [0.315521  , 0.684479  ],
       [0.42539232, 0.57460768],
       [0.35821781, 0.64178219],
       [0.45005269, 0.54994731],
       [0.45005269, 0.54994731],
       [0.36241761, 0.63758239],
       [0.37300827, 0.62699173],
       [0.4120881 , 0.5879119 ],
       [0.43656318, 0.56343682],
       [0.41429712, 0.58570288],
       [0.34575035, 0.65424965],
       [0.34988367, 0.65011633],
       [0.31749192, 0.68250808],
       [0.48405613, 0.51594387],
       [0.39455011, 0.60544989],
       [0.43656318, 0.56343682],
       [0.35195886, 0.64804114],
       [0.34988367, 0.65011633],
       [0.45682636, 0.54317364],
       [0.30964813, 0.69035187],
       [0.31749192, 0.68250808],
       [0.33146932, 0.66853068],
       [0.50227213, 0.49772787],
       [0.40328821, 0.59671179],
       [0.37727954, 0.62272046],
       [0.40988262, 0.59011738],
       [0.47496097, 0.52503903],
       [0.50227213, 0.49772787],
       [0.40109769, 0.59890231],
       [0.36241761, 0.63758239],
       [0.46361604, 0.53638396],
       [0.36031504, 0.63968496],
       [0.40548259, 0.59451741],
       [0.49316186, 0.50683814],
       [0.42539232, 0.57460768],
       [0.44105027, 0.55894973],
       [0.40768075, 0.59231925],
       [0.43656318, 0.56343682],
       [0.48178111, 0.51821889],
       [0.36031504, 0.63968496],
       [0.38156995, 0.61843005],
       [0.30964813, 0.69035187],
       [0.32344386, 0.67655614],
       [0.4165096 , 0.5834904 ],
       [0.47723344, 0.52276656],
       [0.40548259, 0.59451741],
       [0.42539232, 0.57460768],
       [0.49316186, 0.50683814],
       [0.33551947, 0.66448053],
       [0.50227213, 0.49772787],
       [0.36452546, 0.63547454],
       [0.49543924, 0.50456076],
       [0.47496097, 0.52503903],
       [0.4977168 , 0.5022832 ],
       [0.31159906, 0.68840094],
       [0.36031504, 0.63968496],
       [0.33551947, 0.66448053],
       [0.43208645, 0.56791355],
       [0.42539232, 0.57460768],
       [0.3214534 , 0.6785466 ],
       [0.3135567 , 0.6864433 ],
       [0.35403966, 0.64596034],
       [0.34369235, 0.65630765],
       [0.38587892, 0.61412108],
       [0.3375537 , 0.6624463 ],
       [0.44329748, 0.55670252],
       [0.49999447, 0.50000553],
       [0.36452546, 0.63547454],
       [0.46588239, 0.53411761],
       [0.38804017, 0.61195983],
       [0.42762079, 0.57237921],
       [0.3416402 , 0.6583598 ],
       [0.49316186, 0.50683814],
       [0.50227213, 0.49772787],
       [0.39891111, 0.60108889],
       [0.35821781, 0.64178219],
       [0.3416402 , 0.6583598 ],
       [0.33349133, 0.66650867],
       [0.48860805, 0.51139195],
       [0.35821781, 0.64178219],
       [0.45230865, 0.54769135],
       [0.32744398, 0.67255602],
       [0.45005269, 0.54994731],
       [0.34369235, 0.65630765],
       [0.49316186, 0.50683814],
       [0.37727954, 0.62272046],
       [0.32344386, 0.67655614],
       [0.39020584, 0.60979416],
       [0.4863318 , 0.5136682 ],
       [0.39455011, 0.60544989],
       [0.39237585, 0.60762415],
       [0.3194694 , 0.6805306 ],
       [0.4165096 , 0.5834904 ],
       [0.36031504, 0.63968496],
       [0.44329748, 0.55670252],
       [0.43208645, 0.56791355],
       [0.42539232, 0.57460768],
       [0.43208645, 0.56791355],
       [0.45682636, 0.54317364],
       [0.37514147, 0.62485853],
       [0.41872544, 0.58127456],
       [0.35195886, 0.64804114],
       [0.34988367, 0.65011633],
       [0.45682636, 0.54317364],
       [0.45682636, 0.54317364],
       [0.315521  , 0.684479  ],
       [0.46815015, 0.53184985],
       [0.43880548, 0.56119452],
       [0.43880548, 0.56119452],
       [0.356126  , 0.643874  ],
       [0.42316688, 0.57683312],
       [0.32544074, 0.67455926],
       [0.3135567 , 0.6864433 ],
       [0.37088   , 0.62912   ],
       [0.39020584, 0.60979416],
       [0.38156995, 0.61843005],
       [0.356126  , 0.643874  ],
       [0.3194694 , 0.6805306 ],
       [0.44779878, 0.55220122],
       [0.48860805, 0.51139195],
       [0.46815015, 0.53184985],
       [0.315521  , 0.684479  ],
       [0.47723344, 0.52276656],
       [0.3194694 , 0.6805306 ],
       [0.41429712, 0.58570288],
       [0.43880548, 0.56119452],
       [0.42762079, 0.57237921],
       [0.44779878, 0.55220122],
       [0.47723344, 0.52276656],
       [0.46815015, 0.53184985],
       [0.32344386, 0.67655614],
       [0.36031504, 0.63968496],
       [0.41429712, 0.58570288],
       [0.40109769, 0.59890231],
       [0.39891111, 0.60108889],
       [0.31749192, 0.68250808],
       [0.45682636, 0.54317364],
       [0.36031504, 0.63968496],
       [0.45230865, 0.54769135],
       [0.34575035, 0.65424965],
       [0.48860805, 0.51139195],
       [0.34781414, 0.65218586],
       [0.33146932, 0.66853068],
       [0.40548259, 0.59451741],
       [0.30964813, 0.69035187],
       [0.50227213, 0.49772787],
       [0.33551947, 0.66448053],
       [0.44329748, 0.55670252],
       [0.38587892, 0.61412108],
       [0.38372215, 0.61627785],
       [0.32945352, 0.67054648],
       [0.47268954, 0.52731046],
       [0.3135567 , 0.6864433 ],
       [0.37514147, 0.62485853],
       [0.3194694 , 0.6805306 ],
       [0.4120881 , 0.5879119 ],
       [0.32744398, 0.67255602],
       [0.31749192, 0.68250808],
       [0.35403966, 0.64596034],
       [0.32744398, 0.67255602],
       [0.39891111, 0.60108889],
       [0.31159906, 0.68840094],
       [0.33349133, 0.66650867],
       [0.39020584, 0.60979416],
       [0.31159906, 0.68840094],
       [0.48860805, 0.51139195],
       [0.44554701, 0.55445299],
       [0.44105027, 0.55894973],
       [0.46361604, 0.53638396],
       [0.3416402 , 0.6583598 ],
       [0.32544074, 0.67455926],
       [0.46815015, 0.53184985],
       [0.3375537 , 0.6624463 ],
       [0.356126  , 0.643874  ],
       [0.38587892, 0.61412108],
       [0.37942239, 0.62057761],
       [0.40988262, 0.59011738],
       [0.45456657, 0.54543343],
       [0.43880548, 0.56119452],
       [0.43432348, 0.56567652],
       [0.4120881 , 0.5879119 ],
       [0.47496097, 0.52503903],
       [0.46815015, 0.53184985],
       [0.32544074, 0.67455926],
       [0.37727954, 0.62272046],
       [0.47041923, 0.52958077],
       [0.37942239, 0.62057761],
       [0.30964813, 0.69035187],
       [0.39020584, 0.60979416],
       [0.44329748, 0.55670252],
       [0.35195886, 0.64804114],
       [0.43432348, 0.56567652],
       [0.44329748, 0.55670252],
       [0.46135119, 0.53864881],
       [0.32945352, 0.67054648],
       [0.33551947, 0.66448053],
       [0.43432348, 0.56567652],
       [0.36875672, 0.63124328],
       [0.37942239, 0.62057761],
       [0.49088476, 0.50911524],
       [0.38372215, 0.61627785],
       [0.31749192, 0.68250808],
       [0.4863318 , 0.5136682 ],
       [0.47496097, 0.52503903],
       [0.36031504, 0.63968496],
       [0.43880548, 0.56119452],
       [0.315521  , 0.684479  ],
       [0.49999447, 0.50000553],
       [0.39455011, 0.60544989],
       [0.49999447, 0.50000553],
       [0.34369235, 0.65630765],
       [0.39020584, 0.60979416],
       [0.46135119, 0.53864881],
       [0.38804017, 0.61195983],
       [0.33551947, 0.66448053],
       [0.37300827, 0.62699173],
       [0.41429712, 0.58570288],
       [0.38587892, 0.61412108],
       [0.35403966, 0.64596034],
       [0.44105027, 0.55894973],
       [0.3375537 , 0.6624463 ],
       [0.35821781, 0.64178219],
       [0.3416402 , 0.6583598 ],
       [0.44779878, 0.55220122],
       [0.47496097, 0.52503903],
       [0.41872544, 0.58127456],
       [0.41429712, 0.58570288],
       [0.38804017, 0.61195983],
       [0.41429712, 0.58570288],
       [0.45682636, 0.54317364],
       [0.3194694 , 0.6805306 ],
       [0.45005269, 0.54994731],
       [0.3214534 , 0.6785466 ],
       [0.41429712, 0.58570288],
       [0.46135119, 0.53864881],
       [0.39455011, 0.60544989],
       [0.44329748, 0.55670252],
       [0.3375537 , 0.6624463 ],
       [0.36663852, 0.63336148],
       [0.37514147, 0.62485853],
       [0.36241761, 0.63758239],
       [0.38156995, 0.61843005],
       [0.36663852, 0.63336148],
       [0.38587892, 0.61412108],
       [0.42762079, 0.57237921],
       [0.36241761, 0.63758239],
       [0.42316688, 0.57683312],
       [0.37514147, 0.62485853],
       [0.45230865, 0.54769135],
       [0.49316186, 0.50683814],
       [0.44779878, 0.55220122],
       [0.32744398, 0.67255602],
       [0.31749192, 0.68250808],
       [0.46588239, 0.53411761],
       [0.38587892, 0.61412108],
       [0.33349133, 0.66650867],
       [0.37088   , 0.62912   ],
       [0.40548259, 0.59451741],
       [0.4977168 , 0.5022832 ],
       [0.4165096 , 0.5834904 ],
       [0.42539232, 0.57460768],
       [0.3375537 , 0.6624463 ],
       [0.36663852, 0.63336148],
       [0.32344386, 0.67655614],
       [0.31749192, 0.68250808],
       [0.36663852, 0.63336148],
       [0.40548259, 0.59451741],
       [0.45230865, 0.54769135],
       [0.47041923, 0.52958077],
       [0.40109769, 0.59890231],
       [0.31159906, 0.68840094],
       [0.36241761, 0.63758239],
       [0.38156995, 0.61843005],
       [0.38156995, 0.61843005],
       [0.36031504, 0.63968496],
       [0.39672856, 0.60327144],
       [0.36241761, 0.63758239],
       [0.45456657, 0.54543343],
       [0.34781414, 0.65218586],
       [0.32945352, 0.67054648],
       [0.46588239, 0.53411761],
       [0.38587892, 0.61412108],
       [0.3194694 , 0.6805306 ],
       [0.46135119, 0.53864881],
       [0.35403966, 0.64596034],
       [0.40548259, 0.59451741],
       [0.50227213, 0.49772787],
       [0.40328821, 0.59671179],
       [0.33146932, 0.66853068],
       [0.50227213, 0.49772787],
       [0.33349133, 0.66650867],
       [0.43880548, 0.56119452],
       [0.48405613, 0.51594387],
       [0.49999447, 0.50000553],
       [0.43432348, 0.56567652],
       [0.39672856, 0.60327144],
       [0.47041923, 0.52958077],
       [0.45230865, 0.54769135],
       [0.31749192, 0.68250808],
       [0.38372215, 0.61627785],
       [0.46135119, 0.53864881],
       [0.37088   , 0.62912   ],
       [0.32544074, 0.67455926],
       [0.41429712, 0.58570288],
       [0.36663852, 0.63336148],
       [0.47496097, 0.52503903],
       [0.39020584, 0.60979416],
       [0.39237585, 0.60762415],
       [0.49316186, 0.50683814],
       [0.32945352, 0.67054648],
       [0.35403966, 0.64596034],
       [0.30964813, 0.69035187],
       [0.40328821, 0.59671179],
       [0.34988367, 0.65011633],
       [0.50227213, 0.49772787],
       [0.38156995, 0.61843005],
       [0.42094456, 0.57905544],
       [0.49543924, 0.50456076],
       [0.42762079, 0.57237921],
       [0.30964813, 0.69035187],
       [0.44105027, 0.55894973],
       [0.42094456, 0.57905544],
       [0.42316688, 0.57683312],
       [0.39020584, 0.60979416],
       [0.3375537 , 0.6624463 ],
       [0.34988367, 0.65011633],
       [0.40548259, 0.59451741],
       [0.46361604, 0.53638396],
       [0.41872544, 0.58127456],
       [0.32544074, 0.67455926],
       [0.46588239, 0.53411761],
       [0.4165096 , 0.5834904 ],
       [0.42762079, 0.57237921],
       [0.36031504, 0.63968496],
       [0.39237585, 0.60762415],
       [0.37942239, 0.62057761],
       [0.44105027, 0.55894973],
       [0.35821781, 0.64178219],
       [0.50227213, 0.49772787],
       [0.46815015, 0.53184985],
       [0.38587892, 0.61412108],
       [0.31159906, 0.68840094],
       [0.3214534 , 0.6785466 ],
       [0.48405613, 0.51594387],
       [0.37727954, 0.62272046],
       [0.3416402 , 0.6583598 ],
       [0.39672856, 0.60327144],
       [0.43208645, 0.56791355],
       [0.41429712, 0.58570288],
       [0.42094456, 0.57905544],
       [0.356126  , 0.643874  ],
       [0.35821781, 0.64178219],
       [0.45908793, 0.54091207],
       [0.4165096 , 0.5834904 ],
       [0.45682636, 0.54317364],
       [0.4977168 , 0.5022832 ],
       [0.37514147, 0.62485853],
       [0.40988262, 0.59011738],
       [0.36663852, 0.63336148],
       [0.44105027, 0.55894973],
       [0.35195886, 0.64804114],
       [0.36031504, 0.63968496],
       [0.36452546, 0.63547454],
       [0.49088476, 0.50911524],
       [0.40988262, 0.59011738],
       [0.45908793, 0.54091207],
       [0.48178111, 0.51821889],
       [0.48860805, 0.51139195],
       [0.40988262, 0.59011738],
       [0.34781414, 0.65218586],
       [0.49316186, 0.50683814],
       [0.44105027, 0.55894973],
       [0.43656318, 0.56343682],
       [0.40988262, 0.59011738],
       [0.45908793, 0.54091207],
       [0.30964813, 0.69035187],
       [0.33349133, 0.66650867],
       [0.49543924, 0.50456076],
       [0.41429712, 0.58570288],
       [0.42539232, 0.57460768],
       [0.4863318 , 0.5136682 ],
       [0.43880548, 0.56119452],
       [0.37300827, 0.62699173],
       [0.36875672, 0.63124328],
       [0.36663852, 0.63336148],
       [0.40988262, 0.59011738],
       [0.40109769, 0.59890231],
       [0.36875672, 0.63124328],
       [0.33959397, 0.66040603],
       [0.39020584, 0.60979416],
       [0.34575035, 0.65424965],
       [0.34369235, 0.65630765],
       [0.30964813, 0.69035187],
       [0.47496097, 0.52503903],
       [0.40548259, 0.59451741],
       [0.44779878, 0.55220122],
       [0.38587892, 0.61412108],
       [0.41429712, 0.58570288],
       [0.44105027, 0.55894973],
       [0.315521  , 0.684479  ],
       [0.30964813, 0.69035187],
       [0.32344386, 0.67655614],
       [0.36663852, 0.63336148],
       [0.42316688, 0.57683312],
       [0.3135567 , 0.6864433 ],
       [0.37300827, 0.62699173],
       [0.32744398, 0.67255602],
       [0.46588239, 0.53411761],
       [0.4863318 , 0.5136682 ],
       [0.37727954, 0.62272046],
       [0.49543924, 0.50456076],
       [0.42316688, 0.57683312],
       [0.37300827, 0.62699173],
       [0.4120881 , 0.5879119 ],
       [0.3214534 , 0.6785466 ],
       [0.32344386, 0.67655614],
       [0.44554701, 0.55445299],
       [0.42762079, 0.57237921],
       [0.45005269, 0.54994731],
       [0.4977168 , 0.5022832 ],
       [0.49543924, 0.50456076],
       [0.43208645, 0.56791355],
       [0.46135119, 0.53864881],
       [0.42094456, 0.57905544],
       [0.45005269, 0.54994731],
       [0.41429712, 0.58570288],
       [0.32344386, 0.67655614],
       [0.37727954, 0.62272046],
       [0.37942239, 0.62057761],
       [0.4977168 , 0.5022832 ],
       [0.47496097, 0.52503903],
       [0.37300827, 0.62699173],
       [0.40328821, 0.59671179],
       [0.33959397, 0.66040603],
       [0.45230865, 0.54769135],
       [0.38372215, 0.61627785],
       [0.42094456, 0.57905544],
       [0.49088476, 0.50911524],
       [0.33551947, 0.66448053],
       [0.42316688, 0.57683312],
       [0.40768075, 0.59231925],
       [0.48405613, 0.51594387],
       [0.3214534 , 0.6785466 ],
       [0.46588239, 0.53411761],
       [0.3214534 , 0.6785466 ],
       [0.37514147, 0.62485853],
       [0.35403966, 0.64596034],
       [0.49088476, 0.50911524],
       [0.34575035, 0.65424965],
       [0.34575035, 0.65424965],
       [0.38156995, 0.61843005],
       [0.36663852, 0.63336148],
       [0.43432348, 0.56567652],
       [0.48405613, 0.51594387],
       [0.31159906, 0.68840094],
       [0.30964813, 0.69035187],
       [0.40548259, 0.59451741],
       [0.45456657, 0.54543343],
       [0.34781414, 0.65218586],
       [0.32945352, 0.67054648],
       [0.31159906, 0.68840094],
       [0.45005269, 0.54994731],
       [0.49543924, 0.50456076],
       [0.33146932, 0.66853068],
       [0.34781414, 0.65218586],
       [0.31749192, 0.68250808],
       [0.38372215, 0.61627785],
       [0.38587892, 0.61412108],
       [0.32544074, 0.67455926],
       [0.41872544, 0.58127456],
       [0.39891111, 0.60108889],
       [0.49316186, 0.50683814],
       [0.356126  , 0.643874  ],
       [0.48178111, 0.51821889],
       [0.46588239, 0.53411761],
       [0.36875672, 0.63124328],
       [0.43208645, 0.56791355],
       [0.49543924, 0.50456076],
       [0.48178111, 0.51821889],
       [0.48178111, 0.51821889],
       [0.33551947, 0.66448053],
       [0.32544074, 0.67455926],
       [0.39020584, 0.60979416],
       [0.44779878, 0.55220122],
       [0.35821781, 0.64178219],
       [0.46361604, 0.53638396],
       [0.35195886, 0.64804114],
       [0.315521  , 0.684479  ],
       [0.36031504, 0.63968496],
       [0.42985219, 0.57014781],
       [0.36663852, 0.63336148],
       [0.49543924, 0.50456076],
       [0.38372215, 0.61627785],
       [0.46815015, 0.53184985],
       [0.45682636, 0.54317364],
       [0.34369235, 0.65630765],
       [0.49088476, 0.50911524]])

### Modelo con todas las variables

In [13]:
X1 = df.drop(columns=['HeartDisease'])
y1 = df['HeartDisease']

logit_total = LogisticRegression()
    
logit_total.fit(X1, y1)

print("Beta cero:", logit_total.intercept_[0])
print("Betas uno a n:", logit_total.coef_[0])

Beta cero: 7.069513080025965
Betas uno a n: [ 0.05036482 -0.02863074 -0.01585793 -0.0251093  -0.01787389]

### Calcular los accuracy, precision, recall y specificity para diferentes threshold (0.3, 0.5, 0.8)

In [ ]:
threshold = 0.3
ypred = (logit_total.predict_proba(X1)[:, 1] >= threshold).astype(int)
def classify_row(row):
    if row["ypred"] == 1 and row["y"] == 1:
        return "TP"
    elif row["ypred"] == 1 and row["y"] == 0:
        return "FP"
    elif row["ypred"] == 0 and row["y"] == 0:
        return "TN"
    elif row["ypred"] == 0 and row["y"] == 1:
        return "FN"

table = pd.DataFrame({
    "predict_proba": logit_total.predict_proba(X1)[:, 1],
    "ypred": ypred,
    "y": y
})
table["classification"] = table.apply(classify_row, axis=1)
print(table)

#Calcular Accuracy, Recall, Precision y Specificity
TP = np.sum((table["ypred"] == 1) & (table["y"] == 1))
FP = np.sum((table["ypred"] == 1) & (table["y"] == 0))
TN = np.sum((table["ypred"] == 0) & (table["y"] == 0))
FN = np.sum((table["ypred"] == 0) & (table["y"] == 1))

accuracy = (TP + TN) / (TP + FP + TN + FN)
recall = TP / (TP + FN) if (TP + FN) != 0 else 0
precision = TP / (TP + FP) if (TP + FP) != 0 else 0
specificity = TN / (TN + FP) if (TN + FP) != 0 else 0

print(f"Accuracy: {accuracy}")
print(f"Recall: {recall}")
print(f"Precision: {precision}")
print(f"Specificity: {specificity}")

     predict_proba  ypred  y classification
0         0.890145      1  1             TP
1         0.647818      1  0             FP
2         0.828403      1  1             TP
3         0.942247      1  1             TP
4         0.651231      1  1             TP
..             ...    ... ..            ...
495       0.067769      0  0             TN
496       0.150465      0  0             TN
497       0.741009      1  0             FP
498       0.916472      1  1             TP
499       0.318061      1  0             FP

[500 rows x 4 columns]
Accuracy: 0.708
Recall: 0.9366666666666666
Precision: 0.6887254901960784
Specificity: 0.365

In [ ]:
threshold2 = 0.5
ypred2 = (logit_total.predict_proba(X1)[:, 1] >= threshold2).astype(int)

table2 = pd.DataFrame({
    "predict_proba": logit_total.predict_proba(X1)[:, 1],
    "ypred": ypred2,
    "y": y
})
table2["classification"] = table2.apply(classify_row, axis=1)
print(table2)

#Calcular Accuracy, Recall, Precision y Specificity
TP2 = np.sum((table2["ypred"] == 1) & (table2["y"] == 1))
FP2 = np.sum((table2["ypred"] == 1) & (table2["y"] == 0))
TN2 = np.sum((table2["ypred"] == 0) & (table2["y"] == 0))
FN2 = np.sum((table2["ypred"] == 0) & (table2["y"] == 1))

accuracy2 = (TP2 + TN2) / (TP2 + FP2 + TN2 + FN2)
recall2 = TP2 / (TP2 + FN2) if (TP2 + FN2) != 0 else 0
precision2 = TP2 / (TP2 + FP2) if (TP2 + FP2) != 0 else 0
specificity2 = TN2 / (TN2 + FP2) if (TN2 + FP2) != 0 else 0

print(f"Accuracy: {accuracy2}")
print(f"Recall: {recall2}")
print(f"Precision: {precision2}")
print(f"Specificity: {specificity2}")

     predict_proba  ypred  y classification
0         0.890145      1  1             TP
1         0.647818      1  0             FP
2         0.828403      1  1             TP
3         0.942247      1  1             TP
4         0.651231      1  1             TP
..             ...    ... ..            ...
495       0.067769      0  0             TN
496       0.150465      0  0             TN
497       0.741009      1  0             FP
498       0.916472      1  1             TP
499       0.318061      0  0             TN

[500 rows x 4 columns]
Accuracy: 0.73
Recall: 0.7933333333333333
Precision: 0.7652733118971061
Specificity: 0.635

In [21]:
threshold3 = 0.8
ypred3 = (logit_total.predict_proba(X1)[:, 1] >= threshold3).astype(int)

table3 = pd.DataFrame({
    "predict_proba": logit_total.predict_proba(X1)[:, 1],
    "ypred": ypred3,
    "y": y
})
table3["classification"] = table3.apply(classify_row, axis=1)
print(table3)

#Calcular Accuracy, Recall, Precision y Specificity
TP3 = np.sum((table3["ypred"] == 1) & (table3["y"] == 1))
FP3 = np.sum((table3["ypred"] == 1) & (table3["y"] == 0))
TN3 = np.sum((table3["ypred"] == 0) & (table3["y"] == 0))
FN3 = np.sum((table3["ypred"] == 0) & (table3["y"] == 1))

accuracy3 = (TP3 + TN3) / (TP3 + FP3 + TN3 + FN3)
recall3 = TP3 / (TP3 + FN3) if (TP3 + FN3) != 0 else 0
precision3 = TP3 / (TP3 + FP3) if (TP3 + FP3) != 0 else 0
specificity3 = TN3 / (TN3 + FP3) if (TN3 + FP3) != 0 else 0

print(f"Accuracy: {accuracy3}")
print(f"Recall: {recall3}")
print(f"Precision: {precision3}")
print(f"Specificity: {specificity3}")

     predict_proba  ypred  y classification
0         0.890145      1  1             TP
1         0.647818      0  0             TN
2         0.828403      1  1             TP
3         0.942247      1  1             TP
4         0.651231      0  1             FN
..             ...    ... ..            ...
495       0.067769      0  0             TN
496       0.150465      0  0             TN
497       0.741009      0  0             TN
498       0.916472      1  1             TP
499       0.318061      0  0             TN

[500 rows x 4 columns]
Accuracy: 0.636
Recall: 0.44666666666666666
Precision: 0.8933333333333333
Specificity: 0.92